Revert "Add settings items for debugging token state"
This reverts commit 726646058d4a1dc90924ec2a8802c98e79cadcc3.

Was causing a crash when clicking the add button.
It was from mismatch in Compose artifacts. I did add
a new artifact to show marquee text but was of different
version than other artifacts.

Crash was
FATAL EXCEPTION: main
Process: com.ramitsuri.choresclient.android.debug, PID: 10752
java.lang.NoSuchFieldError: No static field $stable of type I in class Landroidx/compose/foundation/text/KeyboardActions; or its superclasses (declaration of 'androidx.compose.foundation.text.KeyboardActions' appears in /data/app/~~YyOe78X6Rn8sBiidFmMC1w==/com.ramitsuri.choresclient.android.debug-MUAXt2n5fBwGCbLJGmdoJg==/base.apk)
at androidx.compose.material3.OutlinedTextFieldKt$OutlinedTextField$2.invoke(OutlinedTextField.kt:184)
at androidx.compose.material3.OutlinedTextFieldKt$OutlinedTextField$2.invoke(OutlinedTextField.kt:159)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
at androidx.compose.material3.OutlinedTextFieldKt.OutlinedTextField(OutlinedTextField.kt:159)
at com.ramitsuri.choresclient.android.ui.task.AddEditTaskScreenKt$AddEditTaskContent$3.invoke(AddEditTaskScreen.kt:204)
at com.ramitsuri.choresclient.android.ui.task.AddEditTaskScreenKt.Name(AddEditTaskScreen.kt:313)
at com.ramitsuri.choresclient.android.ui.task.AddEditTaskScreenKt$AddEditTaskContent$3.invoke(AddEditTaskScreen.kt:215)